#pragma once

enum RobotBehavior {
    ROBOT_BEHAVIOR_NEUTRAL = 0,
    ROBOT_BEHAVIOR_LISTENING,
    ROBOT_BEHAVIOR_THINKING,
    ROBOT_BEHAVIOR_SPEAKING,
    ROBOT_BEHAVIOR_AFFIRM,
    ROBOT_BEHAVIOR_DENY,
    ROBOT_BEHAVIOR_AMUSED,
    ROBOT_BEHAVIOR_SARCASTIC,
    ROBOT_BEHAVIOR_CONFUSED,
    ROBOT_BEHAVIOR_WARNING,
    ROBOT_BEHAVIOR_CELEBRATE,
    ROBOT_BEHAVIOR_HAPPY,
    ROBOT_BEHAVIOR_CURIOUS,
    ROBOT_BEHAVIOR_SURPRISED,
    ROBOT_BEHAVIOR_WORRIED,
    ROBOT_BEHAVIOR_SAD,
    ROBOT_BEHAVIOR_SATISFIED,
    ROBOT_BEHAVIOR_GENTLE,
    ROBOT_BEHAVIOR_EXPLORE,
};
